// ========== THEMES CONFIGURATION ==========

export const THEMES = {
  // ─── THEME 1: DARK GOLD LUXURY (DEFAULT — MATCHES REFERENCE IMAGE) ───────────
  'midnight-navy': {
    id: 'midnight-navy',
    name: 'Dark Gold',
    description: 'Dark luxury — gold accents, premium dashboard',
    swatch: '#0d1117',
    swatchSecondary: '#c9a84c',

    bg:               '#0d1117',
    cardBg:           '#161b26',
    cardInputBg:      '#1e2638',
    border:           '#2a3447',
    headerText:       '#ffffff',
    textPrimary:      '#e2e8f0',
    textMuted:        '#8892a4',
    accent:           '#c9a84c',
    accentLight:      '#2a2416',
    accentText:       '#fcd34d',
    btnPrimary:       '#c9a84c',
    btnPrimaryText:   '#0d1117',
    btnOutlineBorder: '#3d4a5c',
    sliderThumb:      '#c9a84c',
    danger:           '#ef4444',
    dangerLight:      '#3d1a1a',
    tabActive:        '#c9a84c',
    tabActiveText:    '#0d1117',
    statHighlight:    '#1e2638',
    statHighlightText:'#ffffff',
    divider:          '#2a3447',
  },

  // ─── THEME 2: DESERT GOLD ──────────────────────────────────────────────────
  // Warm ivory background, deep bronze card headers, liquid gold accents.
  // Inspired by Dubai's desert luxury aesthetic.
  'desert-gold': {
    id: 'desert-gold',
    name: 'Desert Gold',
    description: 'Warm ivory & burnished bronze — Dubai desert luxury',
    swatch: '#8B5E2A',
    swatchSecondary: '#D4A843',

    bg:               '#F5EFE3',
    cardBg:           '#FFFDF7',
    cardInputBg:      '#FAF6EE',
    border:           '#7A4F1E',
    headerText:       '#FFF8EC',
    textPrimary:      '#3D2200',
    textMuted:        '#8B6840',
    accent:           '#D4A843',
    accentLight:      '#FDF3D0',
    accentText:       '#5C3A00',
    btnPrimary:       '#8B5E2A',
    btnPrimaryText:   '#FFF8EC',
    btnOutlineBorder: '#7A4F1E',
    sliderThumb:      '#8B5E2A',
    danger:           '#C0392B',
    dangerLight:      '#FDECEA',
    tabActive:        '#8B5E2A',
    tabActiveText:    '#FFF8EC',
    statHighlight:    '#5C3600',
    statHighlightText:'#FFF8EC',
    divider:          '#C8A882',
  },

  // ─── THEME 3: EMERALD VAULT ────────────────────────────────────────────────
  // Deep hunter green with platinum accents and cream backgrounds.
  // Evokes private banking, institutional wealth.
  'emerald-vault': {
    id: 'emerald-vault',
    name: 'Emerald Vault',
    description: 'Hunter green & platinum — private banking prestige',
    swatch: '#1A3C34',
    swatchSecondary: '#B8C9B0',

    bg:               '#EEF2EE',
    cardBg:           '#FAFCFA',
    cardInputBg:      '#F3F7F3',
    border:           '#1A3C34',
    headerText:       '#E8F5E2',
    textPrimary:      '#0F2018',
    textMuted:        '#4A6855',
    accent:           '#3D8B6E',
    accentLight:      '#DCF0E8',
    accentText:       '#0F3D2A',
    btnPrimary:       '#1A3C34',
    btnPrimaryText:   '#E8F5E2',
    btnOutlineBorder: '#1A3C34',
    sliderThumb:      '#1A3C34',
    danger:           '#C0392B',
    dangerLight:      '#FDECEA',
    tabActive:        '#1A3C34',
    tabActiveText:    '#E8F5E2',
    statHighlight:    '#0F2018',
    statHighlightText:'#E8F5E2',
    divider:          '#A8C4B0',
  },

  // ─── THEME 4: ROSE OBSIDIAN (PREMIUM DARK MODE - MATCHING ATTACHED IMAGE) ──
  // Near-black charcoal page, deep rose/bronze accent, warm off-white cards.
  // Dark-mode adjacent. Bold, high-contrast, modern luxury.
  'rose-obsidian': {
    id: 'rose-obsidian',
    name: 'Rose Obsidian',
    description: 'Charcoal & gold — bold, dark, luxury dashboard',
    swatch: '#111315',
    swatchSecondary: '#c9a84c',

    bg:               '#111315',
    cardBg:           '#1c1e22',
    cardInputBg:      '#131517',
    border:           '#2b2f36',
    headerText:       '#ffffff',
    textPrimary:      '#f3f4f6',
    textMuted:        '#9ca3af',
    accent:           '#c9a84c',
    accentLight:      '#2e2a1b',
    accentText:       '#fcd34d',
    btnPrimary:       '#c9a84c',
    btnPrimaryText:   '#111315',
    btnOutlineBorder: '#4b5563',
    sliderThumb:      '#c9a84c',
    danger:           '#ef4444',
    dangerLight:      '#3f1b1b',
    tabActive:        '#c9a84c',
    tabActiveText:    '#111315',
    statHighlight:    '#c9a84c',
    statHighlightText:'#111315',
    divider:          '#2b2f36',
  },

  // ─── THEME 5: ARCTIC SLATE ────────────────────────────────────────────────
  // Pure cool-grey palette with electric blue accents.
  // Surgical, tech-forward, ultra-clean. Fintech aesthetic.
  'arctic-slate': {
    id: 'arctic-slate',
    name: 'Arctic Slate',
    description: 'Cool grey & electric blue — fintech precision',
    swatch: '#1E3A5F',
    swatchSecondary: '#3B82F6',

    bg:               '#F1F5F9',
    cardBg:           '#FFFFFF',
    cardInputBg:      '#F8FAFC',
    border:           '#1E3A5F',
    headerText:       '#EFF6FF',
    textPrimary:      '#0F172A',
    textMuted:        '#64748b',
    accent:           '#2563EB',
    accentLight:      '#DBEAFE',
    accentText:       '#1E3A8A',
    btnPrimary:       '#1E3A5F',
    btnPrimaryText:   '#EFF6FF',
    btnOutlineBorder: '#1E3A5F',
    sliderThumb:      '#2563EB',
    danger:           '#DC2626',
    dangerLight:      '#FEE2E2',
    tabActive:        '#1E3A5F',
    tabActiveText:    '#EFF6FF',
    statHighlight:    '#1E3A5F',
    statHighlightText:'#EFF6FF',
    divider:          '#CBD5E1',
  },

  // ─── THEME 6: ROYAL BURGUNDY ──────────────────────────────────────────────
  // Deep wine red with champagne gold accents and soft cream surfaces.
  // Aristocratic, premium, opulent. Old-money Dubai.
  'royal-burgundy': {
    id: 'royal-burgundy',
    name: 'Royal Burgundy',
    description: 'Deep wine & champagne gold — aristocratic opulence',
    swatch: '#4A0E1F',
    swatchSecondary: '#C9A84C',

    bg:               '#F2ECF0',
    cardBg:           '#FDF8FB',
    cardInputBg:      '#F7F0F4',
    border:           '#4A0E1F',
    headerText:       '#FAF0F4',
    textPrimary:      '#2D0010',
    textMuted:        '#7B4459',
    accent:           '#C9A84C',
    accentLight:      '#FAF0D7',
    accentText:       '#5C3A00',
    btnPrimary:       '#4A0E1F',
    btnPrimaryText:   '#FAF0F4',
    btnOutlineBorder: '#4A0E1F',
    sliderThumb:      '#4A0E1F',
    danger:           '#B91C1C',
    dangerLight:      '#FEE2E2',
    tabActive:        '#4A0E1F',
    tabActiveText:    '#FAF0F4',
    statHighlight:    '#2D0010',
    statHighlightText:'#FAF0F4',
    divider:          '#C9A0B4',
  },
};

export const THEME_ORDER = [
  'midnight-navy',
  'desert-gold',
  'emerald-vault',
  'rose-obsidian',
  'arctic-slate',
  'royal-burgundy',
];
